# Architecture
arch: effnetv2_s

# ===== Dataset ===== #
data: ../data
set: ImageNet
name: baseline
num_classes: 1000

# ===== Learning Rate Policy ======== #
clip_grad: 5.
optimizer: adamw
lr: 0.001
lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 100
weight_decay: 0.05
momentum: 0.9
batch_size: 128

# ===== Hardware setup ===== #
num_parallel_workers: 8