# Architecture
arch: UNet_3Plus_DeepSup

# ===== Dataset ===== #
data: ../data
set: LiTS2017
name: baseline
num_classes: 1

# ===== Learning Rate Policy ======== #
optimizer: momentum
base_lr: 0.1
warmup_lr: 0.
min_lr: 0.00001
lr_scheduler: cosine_lr
warmup_length: 0.


# ===== Network training config ===== #
amp_level: O3
keep_bn_fp32: True
beta: [0.9, 0.999]
clip_value: 0.05
epochs: 100
weight_decay: 0.000001
momentum: 0.9
batch_size: 128
enable_graph_kernel: False

# ===== Hardware setup ===== #
num_parallel_workers: 12